links:
  - src: hw0
    dst: hw1
    bandwidth_gbs: 120
    latency_ns: 500
  - src: hw1
    dst: hw0
    bandwidth_gbs: 120
    latency_ns: 500
  - src: hw0
    dst: hw2
    bandwidth_gbs: 120
    latency_ns: 500
  - src: hw2
    dst: hw0
    bandwidth_gbs: 120
    latency_ns: 500
  - src: hw1
    dst: hw2
    bandwidth_gbs: 120
    latency_ns: 500
  - src: hw2
    dst: hw1
    bandwidth_gbs: 120
    latency_ns: 500
